gemini:
  api_key: ${GEMINI_API_KEY}  # Lấy từ .env
  model: gemini-2.0-flash
pinecone:
  api_key: ${PINECONE_API_KEY}  # Lấy từ .env
  environment: us-east-1
  index_name: rag-chatbot
elasticsearch: 
  index_name: rag-chatbot
  initialize: false 
embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
  dimension: 384
cache:
  initial_cap: 1000
  distance_metric: COSINE
  similarity_threshold: 0.9 
  ttl: 3600